import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { FluidCardModel, VehicleForm } from '@/types/fluid'
import { getStatusVisual } from './status-colors'

/**
 * Pure decision function: should the report button be enabled?
 * It requires the form to be valid AND at least one fluid result to exist.
 */
export function canGenerateReport(
  form: VehicleForm,
  results: FluidCardModel[] | null,
): boolean {
  if (!results || results.length === 0) return false
  const hasAnyResult = results.some((r) => !r.hasError)
  if (!hasAnyResult) return false
  // Form validation is checked via the same rules
  if (!form.date || !form.vehicleNumber?.trim() || !(Number(form.kmUsage) > 0)) {
    return false
  }
  return true
}

export interface GenerateReportInput {
  form: VehicleForm
  results: FluidCardModel[]
}

/**
 * Generates and triggers a download of a PDF report. Pure with respect to
 * the inputs — the side effect is the file download.
 */
export function generateReport({ form, results }: GenerateReportInput): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })

  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('FlowMetrics', 40, 50)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text('Automotive Fluid Condition Report', 40, 70)

  // Divider
  doc.setDrawColor(200)
  doc.line(40, 85, pageWidth - 40, 85)

  // Vehicle metadata
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Vehicle Information', 40, 110)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date:        ${form.date}`, 40, 130)
  doc.text(`Vehicle No:  ${form.vehicleNumber}`, 40, 146)
  doc.text(`Km Usage:    ${form.kmUsage}`, 40, 162)

  // Results table
  const body = results.map((r) => {
    const visual = getStatusVisual(r.status)
    return [
      `${r.icon}  ${r.title}`,
      r.hasError ? 'N/A' : r.primaryMetric,
      visual.label,
    ]
  })

  autoTable(doc, {
    startY: 190,
    head: [['Fluid', 'Reading', 'Status']],
    body,
    styles: { fontSize: 11, cellPadding: 8 },
    headStyles: { fillColor: [37, 99, 235] },
    columnStyles: {
      0: { cellWidth: 180 },
      1: { cellWidth: 180 },
      2: { cellWidth: 120, fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        const status = String(data.cell.raw ?? '').toUpperCase()
        if (status === 'GOOD' || status === 'NORMAL') {
          data.cell.styles.textColor = [22, 101, 52]
        } else if (status === 'WARNING' || status === 'BAD') {
          data.cell.styles.textColor = [161, 98, 7]
        } else if (status === 'CRITICAL') {
          data.cell.styles.textColor = [185, 28, 28]
        } else {
          data.cell.styles.textColor = [82, 82, 82]
        }
      }
    },
  })

  // Footer
  const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } })
    .lastAutoTable?.finalY ?? 300
  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text(
    `Generated by FlowMetrics on ${new Date().toLocaleString()}`,
    40,
    finalY + 30,
  )

  const filename = `FlowMetrics_${form.vehicleNumber}_${form.date}.pdf`
  doc.save(filename)
}
